### ISSUE TITLE
Step-up system identification

### ISSUE THREAD

**Issue by pattacini** [tacman-fp7/tactile-control#3]
Run a series of batch data acquisitions with step-up input.

In each batch we vary the tactile feedback starting point and the amplitude of the step-up input.

**Comment by pattacini** [comment]
@massimoregoli, can you report here on the conditions you established for carrying out the experiments?

**Comment by massimoregoli** [comment]
I used the index finger of the right hand of the black iCub to carry out the following _batches_:

| No. | Starting taxel value [-] | Starting voltage [PWM] | Applied step-up voltage [PWM] | No. of repetitions |
| :-: | :-: | :-: | :-: | :-: |
| 1 | 80 | 0 | 1000 | 6 |
| 2 | 140 | 0 | 1000 | 6 |
| 3 | 80 | 0 | 700 | 6 |
| 4 | 80 | 0 | 500 | 6 |
| 5 | 80 | 0 | 400 | 6 |
| 6 | 50 | 0 | 300 | 6 |
| 7 | 50 | 0 | 800 | 6 |
| 8 | 170 | 0 | 1000 | 6 |

The finger has been kept in touch throughout the whole experiment.

**Comment by pattacini** [comment]
I've rearranged data in a table.
I'd avoid the notation `tax -> pwm` :)

**Comment by pattacini** [comment]
Were the _batches_ subsequent according to the order reported in the table?

**Comment by massimoregoli** [comment]
ok :-). Yes thery are.

**Comment by pattacini** [comment]
Therefore, from batch-1 to batch-2 did you basically apply a ramp-up to get 140 tax?

**Comment by pattacini** [comment]
@massimoregoli, try the following in matlab (`robust control toolbox` is required):

``` matlab
% define uncertain real parameters 'tau' and 'A' with given nominal values and variations
tau=ureal('tau',0.75,'PlusMinus',0.3);
A=ureal('A',0.225,'PlusMinus',0.03);
s=tf('s');
plant=A/(tau*s+1); % define the uncertain plant
wc=2*pi*1/2; % cut-off angular frequency
controller=pidtune(plant,'PI',wc); % design the PI controller achieving wc
sys=feedback(controller*plant,1); % close the loop
subplot(121); step(plant);
subplot(122); step(sys);
```

![response](https://cloud.githubusercontent.com/assets/3738070/6115696/d038e2f8-b0a7-11e4-9bc1-9f5058cf35c0.png)

The **PI robust design** comes out with the following gains: `Kp=6.85`, `Ki=28.5`.

**Comment by pattacini** [comment]
Using `pidTuner` we have more degrees of freedom for the design.
For example, we can obtain the following closed-loop response:

![response](https://cloud.githubusercontent.com/assets/3738070/6124652/97e75df4-b10f-11e4-85ab-da8b16dfeeac.png)

The gains are: `Kp=4.55`, `Ki=6.9`, `Kd=0.441`.
