### ISSUE TITLE
Gaps in tactile data retrieval

### ISSUE THREAD

**Issue by pattacini** [tacman-fp7/tactile-control#4]
Check whether gaps in tactile data are present also while using `yarpdatadumper`. If so, open up a new issue here: https://github.com/robotology/icub-main/issues.

**Comment by massimoregoli** [comment]
Solved, data gathered using yarpdatadumper was correct, gaps arose at a higher level

**Comment by pattacini** [comment]
Well done.
Move on with #2 now.
