### ISSUE TITLE
Step-down system identification

### ISSUE THREAD

**Issue by pattacini** [tacman-fp7/tactile-control#5]
Repeat the identification experiment as per #3 but with step-down input

**Comment by massimoregoli** [comment]
I used the index finger of the right hand of the black iCub to carry out the following _batches_:

| No. | Starting taxel value [-] | Starting voltage [PWM] | Applied step-down voltage [PWM] | No. of repetitions |
| :-: | :-: | :-: | :-: | :-: |
| 1 | 250 | 1000 | -1100 | 6 |
| 2 | 238 | 1000 | -1150 | 6 |
| 3 | 246 | 1000 | -1200 | 6 |
| 4 | 254 | 600 | -700 | 6 |
| 5 | 234 | 600 | -750 | 6 |
| 6 | 251 | 600 | -800 | 6 |

The finger lost contact after every repetition of every batch.

**Comment by pattacini** [comment]
The plant model employed during the identification has one zero and two under-damped poles. Interestingly, we have a non-minimum zero in the identified plant.

![response](https://cloud.githubusercontent.com/assets/3738070/6134602/df47ba4c-b162-11e4-933a-0d6701651b8f.png)

A robust **PI** controller with gains `Kp=1.59`, `Ki=1.14` allows for driving the plant towards the set-point.
